---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4518933568-SfQvifuivs723K0X1O3U4Jz7B2rax91JLd7upSo
:access_token_secret: plzFV2nOVT5BcZ8Oe4Pxg1CAsWdOLmBpEkdazn1TMEipe
